all:
  children:
    docker:
      hosts:
        35.237.206.45:
    manager:
      hosts:      
        34.75.89.102:
    worker:
      hosts:
        104.196.20.27:
    nginx:
      hosts:
        34.73.93.246:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: jenkins
    ansible_ssh_private_key_file: '/home/jenkins/.ssh/id_rsa'