[manager]
manager-swarm

[manager:vars]
ansible_user=jenkins
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file=~/.ssh/id_rsa

[worker]
worker-swarm

[worker:vars]
ansible_user=jenkins
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file=~/.ssh/id_rsa

[nginx]
nginx-project

[nginx:vars]
ansible_user=jenkins
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_ssh_private_key_file=~/.ssh/id_rsa