---
- name: install docker
  become: true
  hosts: nginx-project
  roles:
  - docker

- name: install docker
  become: true
  hosts: manager-swarm
  roles:
  - docker

- name: install docker
  become: true
  hosts: worker-swarm
  roles:
  - docker
  
- name: initialize docker swarm
  become: true
  hosts: manager-swarm
  roles:
  - manager

- name: add worker to swarm
  become: true
  hosts: worker-swarm
  roles:
  - worker